using UnityEngine;

public class InfluenceState : MonoBehaviour
{
    // Definimos el Enum que tus otros scripts están buscando
    public enum EstadoInfluencia { Corrupto, Neutral, Sanado }

    private static InfluenceState _instance;
    public static InfluenceState Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = UnityEngine.Object.FindFirstObjectByType<InfluenceState>();
                if (_instance == null)
                {
                    GameObject go = new GameObject("InfluenceState_AutoGenerated");
                    _instance = go.AddComponent<InfluenceState>();
                }
            }
            return _instance;
        }
    }

    // Método que pide EleccionInfluencias
    public static InfluenceState EnsureInstance() => Instance;

    [Header("Configuración")]
    public float currentInfluence = 0f;
    private const string SAVE_KEY = "PlayerInfluence";

    public delegate void OnInfluenceChanged(float newValue);
    public event OnInfluenceChanged OnEstadoChanged;

    // Propiedad que pide HabilidadShaderController
    public EstadoInfluencia CurrentEstado
    {
        get
        {
            if (currentInfluence < -33f) return EstadoInfluencia.Corrupto;
            if (currentInfluence > 33f) return EstadoInfluencia.Sanado;
            return EstadoInfluencia.Neutral;
        }
    }

    private void Awake()
    {
        if (_instance != null && _instance != this)
        {
            Destroy(gameObject);
            return;
        }
        _instance = this;
        DontDestroyOnLoad(gameObject);
        LoadData();
    }

    // Método que pide EleccionInfluencias (alias de AddInfluence)
    public void ModifyValue(float amount)
    {
        currentInfluence = Mathf.Clamp(currentInfluence + amount, -100f, 100f);
        SaveData();
        OnEstadoChanged?.Invoke(currentInfluence);
        Debug.Log($"Influencia modificada: {currentInfluence}. Estado: {CurrentEstado}");
    }

    private void SaveData() => PlayerPrefs.SetFloat(SAVE_KEY, currentInfluence);
    private void LoadData() => currentInfluence = PlayerPrefs.GetFloat(SAVE_KEY, 0f);
}